version: '3.7'

services:
    node-vue:
        build:
            context: ./
            dockerfile: .docker/Dockerfile
            target: 'develop-stage'
        ports:
            - '8080:8080'
        volumes:
            - '.:/app'
        command: /bin/sh -c "yarn serve"